<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="139720" started-at="2022-02-15T08:24:41 IST" finished-at="2022-02-15T08:27:01 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="139720" started-at="2022-02-15T08:24:41 IST" finished-at="2022-02-15T08:27:01 IST">
      <class name="Testpackage.Testcase2">
        <test-method status="PASS" signature="OpenApp()[pri:0, instance:Testpackage.Testcase2@27808f31]" name="OpenApp" is-config="true" duration-ms="91665" started-at="2022-02-15T08:24:42 IST" finished-at="2022-02-15T08:26:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenApp -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:Testpackage.Testcase2@27808f31]" name="test2" duration-ms="37804" started-at="2022-02-15T08:26:13 IST" finished-at="2022-02-15T08:26:51 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://demoapp.skillrary.com/category.php?category=testing                                    ] but found [https://demoapp.skillrary.com/category.php?category=testing]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://demoapp.skillrary.com/category.php?category=testing                                    ] but found [https://demoapp.skillrary.com/category.php?category=testing]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Testpackage.Testcase2.test2(Testcase2.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="CloseApp(org.testng.ITestResult)[pri:0, instance:Testpackage.Testcase2@27808f31]" name="CloseApp" is-config="true" duration-ms="9562" started-at="2022-02-15T08:26:51 IST" finished-at="2022-02-15T08:27:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test2 status=FAILURE method=Testcase2.test2()[pri:0, instance:Testpackage.Testcase2@27808f31] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApp -->
      </class> <!-- Testpackage.Testcase2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
